### ISSUE TITLE
Question about VRAM and RAM requirements

### ISSUE THREAD

**Issue by jojotaro1994** [balazik/ComfyUI-PuLID-Flux#13]
Hi, I would like to know if this implementation has high requirements for system RAM in addition to VRAM. For example, is there a specific amount of RAM needed for it to work properly? Thank you very much for your response!

**Comment by balazik** [comment]
Hi, I never measured the RAM requirements. Its relatively hard to do, because depends on what Flux model and what workflow you use.
For example simple workflow with KSampler and flux1-dev-fp8-e4m3fn, t5xxl_fp8_e4m3fn, flux1_vae and pulid flux loaded as 16bit bfloat takes up ~11 to ~16GB RAM (the range because ComfyUI can load and unload models when generating).

But I recomend at least 32GB RAM when you want to play with ComfyUI else it will swap a lot.
There are also many argument flags that you can use to save memory.

**Comment by Orenji-Tangerine** [comment]
My system RAM peaks at 20GB while VRAM peaks at 15+GB during first run and it takes 80 seconds for a 960x1280 image @ 10 steps, Euler + Simple scheduler

**Comment by balazik** [comment]
No other questions, closing
