### ISSUE TITLE
Why is the background bokeh?

### ISSUE THREAD

**Issue by dzy1128** [balazik/ComfyUI-PuLID-Flux#22]
Why is the background bokeh?The model uses Q8.gguf

**Comment by balazik** [comment]
Hi, I didn't train the Flux1.dev model, go ask somebody from Black Forest Labs or the authors of PuLID Flux model 😉
There are many that fight with this:
[https://www.reddit.com/r/StableDiffusion/comments/1evugwg/dear_flux_devs_please_no_more_depth_of_field/](https://www.reddit.com/r/StableDiffusion/comments/1evugwg/dear_flux_devs_please_no_more_depth_of_field/)

Tip: 
Flux is very sensitive to the prompt. If you focus in the prompt too much on the subject it will focus on the subject if you focus on the background it will focus the background. 

Also try google a bit it helps:
[https://www.reddit.com/r/FluxAI/comments/1ekaehw/has_anyone_found_a_flux_dev_prompt_yet_that/](https://www.reddit.com/r/FluxAI/comments/1ekaehw/has_anyone_found_a_flux_dev_prompt_yet_that/)

Closing (because it has nothing to do with this node).
