### ISSUE TITLE
Apply pulid flux still applies to the model after disconnecting the link.

### ISSUE THREAD

**Issue by Windecay** [balazik/ComfyUI-PuLID-Flux#29]
Why did it apply patches to the checkpoint model? If the weight is 0 or the node is skipped, the face analysis module and EVA clip will still be loaded.

**Comment by balazik** [comment]
Hi,

- Weight has nothing to do with how ComfyUI executes the node graph (loading of models, etc.). Node connections do!
- This is an early Alpha version (I have a newer version in the works, with masking and ModelPatcher, but I can’t publish it because it’s not finished).
- About the model patches, see the Known issues section of the readme.txt.

**Patching:** The problem is that ComfyUI currently doesn’t have the right hooks for applying PuLIDAttention embeddings to the model output, so I needed to improvise. This is why I patch the underlying model directly. When I finish the new version of this node, it will hopefully patch and unpatch the model depending on the connection graph.

**Comment by Windecay** [comment]
Thank you very much!
